# Generated by Django 3.0.3 on 2021-01-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('body_temp', models.IntegerField()),
                ('blood_pres', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('oxygen_satu', models.IntegerField()),
            ],
        ),
    ]
